### ISSUE TITLE
Features > "Scan Client" goes nowhere

### ISSUE THREAD

**Issue by jlmuir** [ControlSystemStudio/controlsystemstudio.github.com#32]
From the home page, navigating at the top to Features > "Scan Client" goes nowhere.

**Comment by berryma4** [comment]
We might need some context.
Which "product" are your using (ie. FRIB, NSLS2, ITER, Community)?
What do you mean by, "goes nowhere"?

**Comment by jlmuir** [comment]
Sorry, I filed this issue against the website repo, so I thought that would be assumed.  I'm talking about the [website](http://controlsystemstudio.org/).

By "goes nowhere," I mean that clicking on the menu item does not take me to a web page about Scan Client; instead my web browser stays on the same page (i.e., the CSS website home page).

**Comment by berryma4** [comment]
Thank you!!

There doesn't seem to be a wiki page for it, so I will point to the internal docs for the time being.
https://github.com/ControlSystemStudio/controlsystemstudio.github.com/commit/5d33d3c57d5d9284d77826f05191a25d718f3c2c

I also cleaned up some whitespace, which should have been another commit.
